### ISSUE TITLE
on failures , URL of report to Puppetboard is broken

### ISSUE THREAD

**Issue by peimanja** [jamtur01/puppet-hipchat#51]
Hi @jamtur01 

on changed or unchanged  report I get a URL on  msg that works and goes straight to puppetboard  report related to this message like : 

http://puppetboard.company.com/report/testclass.i****/1478131021

but when its a failure i just get :

http://puppetboard.company.com/report/testclass.i-*****/

no report # that leads to 

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by jamtur01** [comment]
Sorry. I am not sure. It's been years since I used Puppet and I am not sure how up-to-date this app and it's API is with modern Puppet.

**Comment by jamtur01** [comment]
@james-powis ?

**Comment by james-powis** [comment]
I too have been seeing this issue on all of our puppet installations... The best I can tell is catalog compiles fail to pass a configuration_version to the report api, however on a successful compile but the manifest application fails a configuration_version is generated. 

When i get back into the office I will do a dump on the self object to see what it passes under each situation.

**Comment by james-powis** [comment]
I converted the automated acceptance tests to dump the self object the /tmp/hipchat_notified.txt

I also added a fail block into a manifest to force a failure.

here is the results:
```yaml
---
host: centos-65-x64
time: '2016-12-04T23:24:44.129800039+00:00'
configuration_version: 
transaction_uuid: a35aacac-48e3-4a06-a99b-e278dcbf043c
catalog_uuid: 
code_id: 
cached_catalog_status: not_used
report_format: 6
puppet_version: 4.8.1
kind: apply
status: failed
noop: false
noop_pending: false
environment: production
master_used: 
logs: # <TRUNCATED>
- level: err
  message: 'Could not retrieve catalog from remote server: Error 500 on SERVER: Server
    Error: Evaluation Error: Error while evaluating a Function Call, you suck at /etc/puppetlabs/code/environments/production/manifests/fail.pp:1:1
    on node centos-65-x64'
  source: Puppet
  tags:
  - err
  time: '2016-12-04T23:24:54.635227175+00:00'
  file: 
  line: 
metrics: {}
resource_statuses: {}
corrective_change: false
```

So the question really becomes "is puppet behaving properly" and if the answer to that is "yes" then we should fail back to either passing the node uri or the latest report.

Puppetboard has discussed this problem before: https://github.com/voxpupuli/puppetboard/issues/95

Interestingly running an intentional catalog failure does indeed cause the puppetdb to receive the report (at least as far as puppetboard is reporting...), we too get a report but is the ID a manifestation of puppet, puppetdb or puppetboard?
